-libraryjars /home/carol/jme/WTK2.2/lib/mmapi.jar:/home/carol/jme/WTK2.2/lib/midpapi20.jar:/home/carol/jme/WTK2.2/lib/wma11.jar:/home/carol/jme/WTK2.2/lib/cldcapi10.jar
-injars /home/carol/jme/WTK2.2/apps/DungeonPlus/bin/DungeonPlus.jar
-outjar /tmp/DungeonPlus.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
